// Mock menu items / products with real image paths
export const MENU_ITEMS = [
  {
    id: "p1",
    name: "Classic Cheese Burger",
    description: "Flame-grilled beef patty, melted cheddar, crisp lettuce, and our signature burger sauce.",
    price: 12.99,
    category: "Burgers",
    image: "/src/assets/images/dish-1.png",
    rating: 4.8,
    prepTime: "15 min",
    popular: true,
    calories: 650,
  },
  {
    id: "p2",
    name: "Margherita Gold Pizza",
    description: "San Marzano tomatoes, fresh buffalo mozzarella, basil, and a drizzle of extra virgin olive oil.",
    price: 16.99,
    category: "Pizza",
    image: "/src/assets/images/dish-2.png", // Often pizza or round dish
    rating: 4.7,
    prepTime: "20 min",
    popular: true,
    calories: 890,
  },
  {
    id: "p3",
    name: "Zesty Caesar Salad",
    description: "Crisp romaine hearts, garlic croutons, white anchovies, and creamy parmesan dressing.",
    price: 9.99,
    category: "Salads",
    image: "/src/assets/images/dish-3.png",
    rating: 4.5,
    prepTime: "10 min",
    popular: false,
    calories: 320,
  },
  {
    id: "p4",
    name: "Glazed BBQ Wings",
    description: "Slow-roasted jumbo wings tossed in our house-made hickory smoked BBQ sauce.",
    price: 14.99,
    category: "Starters",
    image: "/src/assets/images/dish-4.png",
    rating: 4.9,
    prepTime: "20 min",
    popular: true,
    calories: 720,
  },
  {
    id: "p5",
    name: "Traditional Carbonara",
    description: "Spaghetti with crispy pancetta, black pepper, and egg yolk sauce (no cream!).",
    price: 13.99,
    category: "Pasta",
    image: "/src/assets/images/dish-5.png",
    rating: 4.6,
    prepTime: "18 min",
    popular: false,
    calories: 780,
  },
  {
    id: "p6",
    name: "Golden Fish & Chips",
    description: "Atlantic cod in a crispy beer batter with hand-cut fries and minted peas.",
    price: 15.99,
    category: "Seafood",
    image: "/src/assets/images/dish-6.png",
    rating: 4.4,
    prepTime: "22 min",
    popular: false,
    calories: 850,
  },
  {
    id: "p7",
    name: "Mediterranean Wrap",
    description: "Grilled chicken, hummus, cucumber salad, and feta cheese in a whole wheat wrap.",
    price: 10.99,
    category: "Wraps",
    image: "/src/assets/images/menu-7.jpg",
    rating: 4.3,
    prepTime: "12 min",
    popular: false,
    calories: 420,
  },
  {
    id: "p8",
    name: "Molten Lava Cake",
    description: "Warm chocolate gateau with a liquid center, served with Madagascan vanilla ice cream.",
    price: 7.99,
    category: "Desserts",
    image: "/src/assets/images/menu-8.jpg",
    rating: 4.9,
    prepTime: "15 min",
    popular: true,
    calories: 490,
  },
  {
    id: "p9",
    name: "Tonkotsu Ramen",
    description: "12-hour pork bone broth, thin noodles, chashu pork, and jammy soft boiled egg.",
    price: 14.99,
    category: "Asian",
    image: "/src/assets/images/menu-9.jpg",
    rating: 4.7,
    prepTime: "25 min",
    popular: true,
    calories: 680,
  },
  {
    id: "p10",
    name: "Double Decker Burger",
    description: "Two 4oz premium beef patties, dual cheese, pickles, and crispy fried onions.",
    price: 15.99,
    category: "Burgers",
    image: "/src/assets/images/menu-1.jpg",
    rating: 4.9,
    prepTime: "18 min",
    popular: true,
    calories: 920,
  },
  {
    id: "p11",
    name: "Pepperoni Passion",
    description: "Loaded with double pepperoni and extra spicy Italian sausage.",
    price: 18.99,
    category: "Pizza",
    image: "/src/assets/images/menu-2.jpg",
    rating: 4.8,
    prepTime: "22 min",
    popular: true,
    calories: 1050,
  },
  {
    id: "p12",
    name: "Berry Blast Smoothie",
    description: "A refreshing blend of blueberries, raspberries, and strawberries with almond milk.",
    price: 6.99,
    category: "Drinks",
    image: "/src/assets/images/home-img-1.png",
    rating: 4.7,
    prepTime: "5 min",
    popular: true,
    calories: 220,
  },
  {
    id: "p13",
    name: "Truffle Fries",
    description: "Crispy fries tossed in black truffle oil and toasted parmesan herbs.",
    price: 8.50,
    category: "Starters",
    image: "/src/assets/images/menu-4.jpg",
    rating: 4.6,
    prepTime: "12 min",
    popular: false,
    calories: 450,
  },
  {
    id: "p14",
    name: "Chicken Enchiladas",
    description: "Corn tortillas stuffed with shredded chicken, topped with spicy red sauce and sour cream.",
    price: 15.50,
    category: "Mexican",
    image: "/src/assets/images/menu-3.jpg",
    rating: 4.5,
    prepTime: "25 min",
    popular: false,
    calories: 820,
  },
  {
    id: "p15",
    name: "Grilled Steak Salad",
    description: "Skirt steak with mixed greens, blue cheese, walnuts, and balsamic reduction.",
    price: 19.99,
    category: "Salads",
    image: "/src/assets/images/dish-4.png",
    rating: 4.9,
    prepTime: "15 min",
    popular: true,
    calories: 540,
  }
];

export const CATEGORIES = [
  "All",
  "Burgers",
  "Pizza",
  "Pasta",
  "Seafood",
  "Asian",
  "Salads",
  "Wraps",
  "Starters",
  "Mexican",
  "Desserts",
  "Drinks",
];

// Mock drivers
export const MOCK_DRIVERS = [
  {
    id: "d1",
    name: "Ahmed Driver",
    phone: "+20 123-456-7890",
    vehicleType: "Motorcycle",
    licensePlate: "DEL-2024",
    rating: 4.9,
    deliveries: 1250,
    status: "available",
    lat: 40.71,
    lng: -74.01,
  },
  {
    id: "d2",
    name: "Maria Garcia",
    phone: "+1 555-0104",
    vehicleType: "Bicycle",
    licensePlate: "BKE-202",
    rating: 4.6,
    deliveries: 218,
    status: "available",
    lat: 40.72,
    lng: -74.0,
  },
  {
    id: "d3",
    name: "James Lee",
    phone: "+1 555-0105",
    vehicleType: "Car",
    licensePlate: "CAR-303",
    rating: 4.9,
    deliveries: 510,
    status: "busy",
    lat: 40.73,
    lng: -73.99,
  },
];
